# Note: If you want to locally override some parameter, create a
# 'local_config.yml' file in this directory (it will be ignored by Git).

input_workbook: 'https://docs.google.com/spreadsheets/d/1r-WxW4JeNoi_gCMc5y2iTlJQnan_LLCF5s_V4ZDDMkI/'

repo_web_url: 'https://github.com/epoch-research/ftm'
repo_url: '${repo_web_url}.git'

cache_dir: '${project_dir}/_cache_'
report_dir: '${project_dir}/_output_'

# Simulation resolution
t_start: 2022
t_end:   2100
t_step:   0.1

# Full automation training requirements distribution
ajeya_dist_url: 'https://docs.google.com/spreadsheets/d/1r-WxW4JeNoi_gCMc5y2iTlJQnan_LLCF5s_V4ZDDMkI/edit#gid=1177136586'
aggressive_ajeya_dist_url: 'https://docs.google.com/spreadsheets/d/1r-WxW4JeNoi_gCMc5y2iTlJQnan_LLCF5s_V4ZDDMkI/edit#gid=701812055'

human_names: true

#------------------------------------------------------------------------------
# Analysis arguments
#------------------------------------------------------------------------------
# You can set here the default arguments of the analysis scripts

diffy:
  max-steps: 200 # number of iterations available in the report
